In [2]:
import numpy as np

### Question1
A is 4 * 4 matrix, B is 1 * 4 array, we got 1 * 4 result

### Answer
Yes, if A is a 4x4 matrix and B is a 1x4 array, performing the matrix multiplication np.matmul(A, B) would result in a 1x4 array. This is because numpy uses broadcasting, allowing the 1x4 array B to be broadcasted to match the shape of the second dimension of the matrix A (4 columns), so that a matrix multiplication can be performed.

It's important to note that the number of columns in A must match the number of rows in B in order for the matrix multiplication to be valid. In this case, the number of columns in A is 4, and the number of rows in B is also 4, so the operation can be performed.

In [12]:
aa = [[1,2],[3,4]]
bb =  [1,2]
np.dot(aa,bb)
np.transpose(np.ones(4))
a = np.array([[1], [2], [3]])
print(a.shape)
a_t = np.transpose(a)
print(a_t.shape)
a_t

b = np.array([1,2,3])
print(b.shape)
b_t = np.transpose(b)
print(b_t.shape)
b_t

(3, 1)
(1, 3)
(3,)
(3,)


array([1, 2, 3])

In [4]:
# Brooadcast to array，因为array本身这个就不算矩阵，很模糊
AA=np.array([
    [0, 1, 1, 1], 
    [0, 0, 1, 1], 
    [1, 0, 0, 1],
    [0, 0, 0, 1],
])
aa = [0.1,0.2,0.3,0.4]
aaa = [[0.1],[0.2],[0.3],[0.4]]
aaaa = [[0.1,0.2,0.3,0.4]]
print(np.matmul(AA,aa))
print(np.matmul(AA,aaa))
print(np.matmul(aa,AA))
#print(np.matmul(AA,aaaa)) vaklue error

[0.9 0.7 0.5 0.4]
[[0.9]
 [0.7]
 [0.5]
 [0.4]]
[0.3 0.1 0.3 1. ]


Dot product of two arrays. Specifically,

If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

### Question2
Array transpose

In [30]:
aa = [[1,2],[3,4]]
bb =  [1,2]
np.dot(aa,bb)
np.transpose(np.ones(4))
a = np.array([[1], [2], [3]])
print(a.shape)
a_t = np.transpose(a)
print(a_t.shape)
a_t

b = np.array([1,2,3])
print(b.shape)
b_t = np.transpose(b)
print(b_t.shape)
b_t

(3, 1)
(1, 3)
(3,)
(3,)


array([1, 2, 3])

### Question3
List Array 的一些操作

In [34]:
aa = [[1,2],[3,4]]

print(aa[:][1])
print(aa[1])

aaa = np.array([[1,2],[3,4]])
print(aaa[1])
print(aaa[:][1]) # 不会报错，但和上面显示一致
print(aaa[:][:][1]) # 不会报错，但和上面显示一致
# 说明list是按index从左至右顺序来处理的
#print(aaa[:1][1]) # 会报错
print(aaa[:1,1]) # 不会报错，实现了切片


[3, 4]
[3, 4]
[3 4]
[3 4]
[3 4]
[2]


1. multiply是elementwise的操作，等同于 *
2. 有多个条件就用while循环
3. while记得要给l+1
4. tokens是['<pad>','the', '.', ',',]类似列表， text_vocab是{'<pad>':1,'the':2, '.':3, ',':4}这种字典类似
5. unqiue返回array
6. array 和 matrix的访问, np.matrix和普通的list、array一些不一样: a)L[0][1]不能访问matrix的元素，要用L[0,1]. b)list不能够用L[0,1]只能用L[0][1]. c)array两种都可以用
7. nonzero()返回的是一个tuple，要取nonzero()[0]
8. test_data_matrix[test_data_matrix.nonzero()] matrix返回的是一个array在这里，所有非零值的index
9. In Python, the sorted() function returns a sorted list of elements from an iterable object (e.g. list, tuple, dict, etc.). 

### Question4
axis = 0 和 axis =1


In [36]:
test_ax = np.array([[1,2,3],[1,2,3],[1,2,3]])
test_ax.sum(axis=0)

array([3, 6, 9])

In [37]:
axx = [-1,-1,3]
np.abs(axx)

array([1, 1, 3])

### Question5
insert(0,'key')的0是代表插入的index位置，与插入的值没有关系

In [53]:
test_insert =[]
test_insert.insert(0,'key')
test_insert.insert(0,'gg')
test_insert

['gg', 'key']

### Question6
[::-1]去除最后一个元素

In [54]:
test_slice = [1,2,3,4]
test_slice[:-1]

[1, 2, 3]

### Question7
关于正则表达式

https://www.zhihu.com/question/48219401

n Python programming, "r" before a string literal means "raw string". Raw strings preserve escape sequences and special characters in their original form and do not interpret them. For example, in a regular string, the escape sequence "\" is used to represent a single backslash, whereas in a raw string, two consecutive backslashes are treated as a single literal backslash. Raw strings are commonly used for regular expressions and file paths.

In [47]:
print(r"\t")
print("---------")
print("\t") #display nothing

\t
---------
	


 For example, given the string "aaa", a greedy match of "a+" would match all three characters, whereas a lazy match of "a+?" would only match the first character.

### Question8
关于dict的一些遍历操作，包括用sorted时的返回值问题

In [56]:
test_dict = {'fruit': 1.0,
 'company': 0.547120747653,
 'apple': 0.41334243636,
 'orange': 0.155466692675,
 'food': 0.147812587177,
 'vegetable': 0.132148274312,
 'tech company': 0.120745147762}

for k,v in test_dict.items():
    print(k,v)

fruit 1.0
company 0.547120747653
apple 0.41334243636
orange 0.155466692675
food 0.147812587177
vegetable 0.132148274312
tech company 0.120745147762


In [58]:
print(sorted(test_dict, key = lambda x: x[1], reverse =True))
print(sorted(test_dict.items(), key = lambda x: x[1], reverse =True))

['fruit', 'orange', 'apple', 'company', 'food', 'vegetable', 'tech company']
[('fruit', 1.0), ('company', 0.547120747653), ('apple', 0.41334243636), ('orange', 0.155466692675), ('food', 0.147812587177), ('vegetable', 0.132148274312), ('tech company', 0.120745147762)]
